### ISSUE TITLE
get new country information

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/countrymaps#3]
We need the country_data information for the new countries. In particular area and population. @JulianHunt4 do you know how files like `country_data/AFG/AFG_general.json` were generated?

```
{
  "name": "Afghanistan", 
  "type": "country", 
  "sub-countries": [], 
  "stats": [
    {
      "type": "POP_TOTL", 
      "label": "Total population", 
      "unit": "million people", 
      "value": "31.29", 
      "rank": "41.0"
    }, 
    {
      "type": "POP_DNST", 
      "label": "Population density", 
      "unit": "people/sq. km", 
      "value": "47.93", 
      "rank": "115.0"
    }, 
    {
      "type": "RUR_POP_PRCT", 
      "label": "Rural population", 
      "unit": "% of total population", 
      "value": "75.73", 
      "rank": "16.0"
    }, 
    {
      "type": "URB_POP_PRCT", 
      "label": "Urban population", 
      "unit": "% of total population",
      "value": "24.27", 
      "rank": "169.0"
    }, 
    {
      "type": "POP_GROWTH", 
      "label": "Population growth", 
      "unit": "% per year", 
      "value": "2.89", 
      "rank": "27.0"
    }, 
    {
      "type": "GDP", 
      "label": "Gross Domestic Product", 
      "unit": "million USD (current)", 
      "value": "17566.0", 
      "rank": "110.0"
    }, 
    {
      "type": "HDI", 
      "label": "Human Development Index", 
      "unit": "(-)", 
      "value": "476.9", 
      "rank": "148.0"
    }, 
    {
      "type": "POV_DDAY", 
      "label": "Poverty headcount ratio at USD 1.90 a day", 
      "unit": "% of total population", 
      "value": "nan", 
      "rank": "nan"
    }, 
    {
      "type": "CO2_EM", 
      "label": "CO2 emissions", 
      "unit":"metric tons/capita", 
      "value": "0.3", 
      "rank": "153.0"
    }]
}

```

**Comment by perrette** [comment]
Maybe there is a script or something that could be uploaded to this repo.

**Comment by perrette** [comment]
Country area is not included in that dataset. Can it be derived from total population and total density? @BarbaraTempl @JulianHunt4  can you control with Ted? I think she generated the dataset in the first place. 
I also have another dataset from Stefan that I could use.

**Comment by perrette** [comment]
@JulianHunt4 ?

**Comment by perrette** [comment]
Country data are used as header in country reports, e.g.
https://isipedia.org/report/future-projections.afg.extreme-events.d786b

**Comment by perrette** [comment]
Stefan provided me with gridded data for urban and rural population, as well as grid cell area, so that I could potentially derive these info with reasonable accuracy for larger countries, but that would not be satisfying for small countries.
 
Probably a better approach is to access the official data for each country (e.g. World Bank), and group that data appropriately. Population, GDP, CO2 emissions are additive, population density could be aggregated based on some assumption about land area (assuming area = population / density ), some other variables could be derived as well. Nevertheless it would be useful to have the original scripts.

Thanks.

**Comment by BarbaraTempl** [comment]
I am not sure why do we need "Country area" ?
Isn`t the country masks are enough for the calculations?

**Comment by BarbaraTempl** [comment]
@JulianHunt4 could answer / clarify it with Ted. Thanks in advance. Worth case: i write to Ted..

**Comment by perrette** [comment]
You are right, we can get that information in various ways, but they all might differ slightly from how things have been done so far, so I would like to know in which way it was derived in the first place.

We need it to express variables in `km^2` instead of `% of land area`.

The problem with country masks is 
- from the grid: small country have an area smaller than a grid cell so they are not well represented in that kind of calculation -- though Stefan might have used that information in the first place.
- from the vector shape, that is more precise, but that is an approximation as well
But `area = population / density` derives directly from the definition of density, so that should do it.

**Comment by JulianHunt4** [comment]
I Mahé, I am sorry for the late reply. I was not aware of this github repository, and I did not receive emails about this conversation. I will go through your questions now.

**Comment by JulianHunt4** [comment]
Hi Mahé, 
I have never seen the JSON file below:
{
  "name": "Afghanistan", 
  "type": "country", 
  "sub-countries": [], 
  "stats": [
    {
      "type": "POP_TOTL", 
      "label": "Total population", 
      "unit": "million people", 
      "value": "31.29", 
      "rank": "41.0"
    }, 
I will ask Yusuke and Ted now to see who created them.

**Comment by rgieseke** [comment]
There should be plenty of ways to automate and document this, there are a couple of Python libraries for accessing the WorldBank API.

E.g.
https://github.com/rufuspollock/world-bank-data
https://github.com/mwouts/world_bank_data
https://github.com/oliversherouse/wbdata
https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#world-bank

As we discussed previosly it would be useful to move this template filling into the same Jinja2 step, but that's probably a separate issue.

**Comment by perrette** [comment]
> I Mahé, I am sorry for the late reply. I was not aware of this github repository, and I did not receive emails about this conversation. I will go through your questions now.

no worry, I could have written an email directly

**Comment by perrette** [comment]
@rgieseke thanks for these links.
I first wanted to make sure how the data were derived in the first place.
Now that we have them (see commit above), we can proceed to any optimization we like.

**Comment by perrette** [comment]
> As we discussed previosly it would be useful to move this template filling into the same Jinja2 step, but that's probably a separate issue.

I'd say this repository is related first and before all to derive country shapefiles + masks and related info + editing the world map, while the python text generator is flexible with respect to indicator variables and text.

At the end the updated country_data with CODE_general.json is copied and present in the isipedia-text-generator (so far it is present in the jinja2 branch only), soon to be merged to the master -- I'm trying to finish that today.

So far I find this distinction useful.
